### ISSUE TITLE
Clicking "Cancel" after Command-Q on Mac quits anyways.

### ISSUE THREAD

**Issue by GrahamKim** [thompsct/SemGen#108]
When you load a model in the Annotator, then hit command-Q to quit, you get two copies of a message that asks you if you want to save the file. If you hit "Cancel", SemGen quits anyways.

Desired behavior: only one message appears, and SemGen does not quit if you hit "Cancel."

**Comment by maxneal** [comment]
The reason this happens is because when you hit command-Q, two things fire:

1) the action associated with the "Quit SemGen" menu item in the SG "File" menu fires, which calls SemGen.quit()
2) the Mac-specific action associated with the "Quit SemGen" menu item in the Mac toolbar also fires, and our OSXAdaptor tells SemGen to fire the SemGen.quit() function.

One solution might be to put the SG toolbar in the Mac toolbar rather than in the main SG frame. Then we could disable the "File > Quit SemGen" item if the user is on a Mac

**Comment by GrahamKim** [comment]
I did notice Command-Q is bound to both the SemGen menu item and the OSX, and so those two things fire. I tried disabling the SemGen menu item key shortcut, but for some reason it looks like OSXAdaptor still fires SemGen.quit() even after canceling.

**Comment by thompsct** [comment]
Looking at the comment for the quithandler in OSXAdapter, it states that the method passed should be a boolean. I changed over, if one of you could see if SemGen still quits when cancel is selected?

**Comment by GrahamKim** [comment]
It works correctly on my end. Thanks Chris!

**Comment by maxneal** [comment]
It looks like things are working correctly on my end. So would it be possible to just disable the shortcut for the File menu if the user is on a Mac?

**Comment by thompsct** [comment]
I don't see why not.

**Comment by maxneal** [comment]
OK I added that in. Could you guys test to make sure things are working on your end?

**Comment by thompsct** [comment]
Cntrl Q works as expected in Windows.

**Comment by GrahamKim** [comment]
Works fine on my end.

**Comment by maxneal** [comment]
Closing this bad boy.
