### ISSUE TITLE
Submodel visualizations are cluttered

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#44]
The names above submodel nodes often overlap for larger models, which clutters the visualization.

**Comment by maxneal** [comment]
Using an invisible rectangle that surrounds both the node its name sounds like a potential solution. Let's try it out and see what happens.

**Comment by rcjames1004** [comment]
I'll work on fixing this tonight.

**Comment by rcjames1004** [comment]
Soooooo, d3 doesn't understand rectangles when applying forces. I misunderstood the code I read when I did background reading. D3 represents everything as infinitely small points "molecules" that have a charge.

Instead of using rectangles to fix this issue I glued submodel labels to hidden "molecules" that repel other nodes and labels. The longer the label the more hidden molecules I attach, which prevents long labels from having vulnerable gaps. I think it's pretty cool. To show the hidden "molecules" change "var ShowHiddenNodes = false;" in hiddenLabelNode.js.

Check in: https://github.com/thompsct/SemGen/commit/b8bebd8e370afad4904aee4bd576ea76c75f76d1

We can add the same logic to dependency node labels by adding "this.addBehavior(HiddenLabelNodeGenerator);" to the constructor in DependencyNode.js. I didn't in this check in because I wasn't sure it was necessary, and we might start to see performance degrade if we use this feature while several nodes are showing (since it can add 2+ hidden nodes for every visible label).

We can test and tweak this as needed to make demo scenarios behave appropriately.
