### ISSUE TITLE
After closing a model on the Stage, dragging another model to the last location of the closed model launches the Merger

### ISSUE THREAD

**Issue by GrahamKim** [thompsct/SemGen#79]

**Comment by thompsct** [comment]
I've managed to track down and fix this error in the Annotator Refactoring branch. 'dragToMerge.js' was storing the loaded models in a global variable and closed models were not getting removed. Separately, in the stage workbench, the call to remove a model was being passed the model object, instead of the model name as it needed.

**Comment by maxneal** [comment]
Nice. Thanks Chris.

M

**Comment by thompsct** [comment]
Fixed
