### ISSUE TITLE
Load and provide heavily used Physical Properties in annotator automatically

### ISSUE THREAD

**Issue by thompsct** [thompsct/SemGen#80]
One feature I plan on adding through the Annotator refactoring is to create a run time library of reference terms that is separate in memory from the model. That way terms can be imported and used without needing to save them in the models themselves.

I suggest we take advantage of this and automatically load the most commonly used properties every time the annotator is started. Not only would it be convenient, but would reduce the chances of an annotator picking the wrong property term.

**Comment by maxneal** [comment]
So this collection of property terms would come from some set of previously annotated models? Like, models in an "example" folder?

**Comment by thompsct** [comment]
I was thinking we could simply provide an agreed upon list in the cfg folder. We could definitely derive the list from the models in the example folder.

**Comment by maxneal** [comment]
OK. 
Also, when you say "That way terms can be imported and used without needing to save them in the models themselves" are you suggesting that we not store reference terms in SemSim OWL models?

**Comment by thompsct** [comment]
Reference terms used within a model would still be stored in that model. What I mean is, you could create local lists of terms and load them independently of whether they're actually used in a particular model ( or even import just the reference terms from a model without assigning them to a data structure). These lists would be saved in their own files.

**Comment by maxneal** [comment]
Yes, this is a good idea. I'd have to look closer, but could the existing ontologyTermsAndNamesCache.txt in the cfg folder be used for this purpose?  Can't recall offhand where it's used in SemGen...

**Comment by thompsct** [comment]
TermsAndNamesCache.txt isn't actually used anywhere as far as I know.

**Comment by maxneal** [comment]
Check out OntologyCache.java (probably should be renamed to OntologyTermCache.java). It's used to build a look-up table of ontology terms and their names so when SG loads an SBML model, SG doesn't have to go to BioPortal to find the term name. If you load an SBML model and there's an ontology term URI in there that isn't in the cache, SG looks up the name in BioPortal, otherwise, it just pulls the name in from the look-up table. I intended it as a cache of ontology terms that would be populated as the user brings in annotations from BioPortal, whether that's through reading in annotated models, or applying annotations manually. Maybe you could build on this...

**Comment by thompsct** [comment]
I actually envision allowing the user to maintain multiple cache files. This way they can have domain specific lists they can choose to import as needed.

The property list would be maintained separately in cfg.

**Comment by thompsct** [comment]
Done.
