### ISSUE TITLE
Singular annotations do not produce reference classes

### ISSUE THREAD

**Issue by thompsct** [thompsct/SemGen#85]
When a component is given a singular annotation, a corresponding reference class is not added to the model or saved.

**Comment by maxneal** [comment]
That's true; the singular annotation currently exists in a <refersTo> axiom only. But do we really need the corresponding reference class in there?  Subclassing a physical property under it's singular annotation URI isn't ontologically correct in the case of biosimulation models. If we annotate some codeword as OPB:Time, we don't want to assert that the codeword's physical property is an instance of OPB:Time. This is because the codeword *represents* the time property in the mdoel. It's not an actual, physical instance of the reference class. BTW I'm currently thinking we should replace the <refersTo> predicate with <hasPhysicalDefinition>.

**Comment by thompsct** [comment]
I was thinking we would add the reference class without sub-classing the annotated component. This way, a model parser can quickly determine time or some other ontology reference term is represented in the model.

**Comment by maxneal** [comment]
Are you thinking about a user outside our group parsing the model with their own code, or are you thinking about how we can streamline our own parser?

**Comment by thompsct** [comment]
Both, the VPR KB parser won't pick it up for example. My standing is we should list all reference terms referred to in the model.

**Comment by maxneal** [comment]
I hear you but all the reference terms are already there in the model. Sounds like you are looking for an easy way to get that list, but adding in more class statements seems redundant to me.

Are you using the SemSim API as part of the VPR KB parsing?  It's currently very easy to get the list of reference terms with the SemSimAPI:

SemSimModel model = ...;
Set<ReferenceOntologyAnnotation> anns = model.getReferenceOntologyAnnotations();

If you're not using the API, what are you using to parse the OWL? An RDF parser?

**Comment by thompsct** [comment]
The advantage is having a consistent way to represent reference terms in both the API and OWL files. It would also allow for a simplified (and faster) routine for reading.

Right now, we have two types of objects for representing reference terms (refers to) : ReferenceOntologyAnnotation and reference term physical objects (which are basically wrappers for ROAs). It is not clear from the API what the difference is or that the physical objects are a specific subtype (refersto) of the ROA or that they don't actually include all references in the model.

For the KB, I actually rewrote the reader since I didn't need any of the computational components. I had not realized there weren't corresponding classes for all 'refersto' annotations in the model. (Another advantage - we could provide options for reading only parts of a model in the API).

**Comment by maxneal** [comment]
The distinction between the ReferenceOntologyAnnotation object and reference term physical objects is that an ROA can use a variety of relations (refersTo, part_of, has_part, etc.). A reference physical object (ReferencePhysicalEntity) is meant to represent a physical entity that has an ROA with <refersTo> as its relation.

I would support refactoring things so that we get rid of the separate reference and custom physical objects. For example, we would just have PhysicalEntity without any subclasses. We could then just include methods within PhysicalEntity that indicate whether an instance has a <refersTo> annotation against a reference ontology or not. That would serve to distinguish between custom and reference terms, I believe. Would that be a solution to the broader issue here?

**Comment by thompsct** [comment]
I've thought of removing the custom/reference distinction, but I think the distinction is useful due to some important differences:
1)  A reference object should be immutable once created.
2) Both objects have methods that don't belong to the other, but are shared with non-physical entities (and reference terms shouldn't have the annotatable interface).

At any rate this solution also doesn't address the core problem that a ReferencePhysicalEntity is just a wrapper for a 'refers_to' annotation, while not all 'refers_to' annotations have such a wrapper. I've done quite a bit of work on this problem in the Annotation refactoring branch.

**Comment by maxneal** [comment]
Chris,

I'm a bit confused so can we set up a video call to talk about these
issues? I think you've been running into some SemSimAPI design choices that
should be fixed, and there are some fundamental changes that I've been
thinking about wrt the refersTo annotations. I want to make sure we're on
the same page. What's your schedule like today?

M

**Comment by thompsct** [comment]
Singular annotations now produce a corresponding subclass.
