### ISSUE TITLE
Variables with same units - Annotator auto-annotating only some of them.

### ISSUE THREAD

**Issue by GrahamKim** [thompsct/SemGen#9]
In SemGen Annotator, some codewords aren't showing the correct codeword button and auto-annotated OPB classes based on units.

This happens in master and Precheckin branch, and with CellML models (haven't tested in Refactoring branch, or with other model formats).

E.g. In beeler_reuter_1977_1.cellml, "slow_inward_current.E_s" and "membrane.V" both have units "mV" , but only the former is auto annotated and identified as property of entity.
![screen shot 2015-01-07 at 11 23 20 pm](https://cloud.githubusercontent.com/assets/6016005/5659282/9c6d4c72-96c4-11e4-9d40-40d2e4046817.png)

![screen shot 2015-01-07 at 11 23 28 pm](https://cloud.githubusercontent.com/assets/6016005/5659288/a48d6b3a-96c4-11e4-8c44-4ebb99035b14.png)

**Comment by maxneal** [comment]
The variable membrane.V *should* be auto-annotated with OPB:Electrical Potential; this is a shortcoming of the current auto-annotation process. When the auto-annotator determines which forces (such as  electrical potentials) it should annotate, one criteria for inclusion is whether the force is solved using an ODE. The way the auto-annotator currently checks for this is using the DataStructure.hasStartValue() method. In SemSim models, only those data structures that are solved with an ODE have a non-null start value. The trouble arises because when we convert CellML models to the SemSim format, the converter actually doesn't capture this start value information. It DOES capture the CellML "initial_value" information, but that has a slightly different meaning than the data structure's "start value".  A CellML initial_value can be used to set the value of a model constant *or* indicate the initial condition for a variable solved using an ODE.  In SemSim models not derived from CellML models, the hasStartValue() only indicates the latter.

So one solution is to amend the CellMLreader so that it identifies the CellML variables that are solved using ODEs. Then, we can use those variables' initial_value numbers for their DataStructure:startValue numbers. This will require parsing the MathML associated with the variable.

There might be other, less involved solutions. Will think about it.

BTW the reason "slow_inward_current.E_s" was successfully annotated was because it depends on "slow_inward_current.Cai", which was identified as an OPB amount property: a concentration. In the auto-annotator logic, any candidate force variable that is mathematically dependent on a confirmed amount should get annotated as an OPB force.

Hope this makes sense.

**Comment by GrahamKim** [comment]
Thanks for the explanation Max.

What would be the pitfall of auto-annotating everything we can from units?
I.e. why are we only auto-annotating forces and flows solved using an ODE?

**Comment by maxneal** [comment]
The reason is because not every variable with units represents a bona fide physical, dynamical property. There are many cases where the variable is simply a constitutive, curve-fitting parameter that has no biological meaning, only mathematical meaning.  We don't want to auto-annotate those with OPB:Dynamical properties; they should be annotated with OPB:Constitutive properties. So we thought of some basic rules we could use for identifying the bona fide dynamical properties. One of the rules we thought would work most of the time is to assume that any variable solved with an ODE is a dynamical property. This is because ODEs usually represent mass and energy conservation laws, and such laws involve the dynamics of bona fide dynamical properties.

**Comment by maxneal** [comment]
I should also mention that the auto-annotator is a work in progress. Currently it attempts to auto-annotate amounts, forces and flows. It should include momenta but that's not in there yet.

The basic logic for what it does currently is:

1) Collect all candidate amounts, forces and flows based on units
2) Identify true amounts based on whether they are solved with an ODE
3) All other candidate amounts that are mathematically dependent on a true amount are also true amounts
4) Any candidate forces that are dependent on a true amount are true forces
5) Any forces solved with an ODE are true forces
6) All other candidate forces that are mathematically dependent on a true forces are also true forces
7) Any candidate flows that are dependent on a true amount or true force are true flows
8) Repeat steps 5 and 6 but for flows 

Hope this sheds some light.

**Comment by dcookUW** [comment]
Max,

Thanks for making this reasoning explicit. Good work. I think you’ve got it down but we’ll see with further testing.

Dan
